import Foundation
import Darwin
import AgentKeeperCore

/// Installs / uninstalls a wrapper shell script as the Codex CLI `notify`
/// target. The wrapper preserves whatever was previously configured (so
/// SkyComputerUseClient et al. keep working) and additionally invokes
/// agentkeeper-hook so we can render Codex state in the menu bar.
///
/// We deliberately avoid pulling in a TOML parser: the edit is narrow,
/// strictly `notify = [...]`, and we keep the prior array as the wrapper's
/// embedded forward target.
enum CodexNotifyInstaller {
    enum InstallError: Error, LocalizedError {
        case writeFailed(String)
        var errorDescription: String? {
            switch self {
            case .writeFailed(let s): return "Failed to update ~/.codex/config.toml: \(s)"
            }
        }
    }

    static var wrapperURL: URL { AppPaths.codexNotifyWrapper }

    static var isInstalled: Bool {
        guard let text = try? String(contentsOf: AppPaths.codexConfig, encoding: .utf8) else { return false }
        return text.contains(wrapperURL.path)
    }

    /// True when the installed wrapper forwards to itself — the symptom of a
    /// previously-corrupted install (re-running `install()` repairs it).
    /// Surfaced in the Diagnostics view.
    static var isSelfReferential: Bool {
        guard let target = readForwardingTargetFromWrapper() else { return false }
        return target.contains(where: { samePath($0, wrapperURL.path) })
    }

    static var isHealthy: Bool { isInstalled && !isSelfReferential }

    @discardableResult
    static func install() throws -> URL {
        AppPaths.bootstrap()
        let configURL = AppPaths.codexConfig
        let fm = FileManager.default

        // Read existing config, parse current `notify` line.
        var text = ""
        if fm.fileExists(atPath: configURL.path) {
            text = (try? String(contentsOf: configURL, encoding: .utf8)) ?? ""
            try backup(configURL, label: "codex-config")
        }

        let forwardTarget = resolveForwardTarget(configArray: extractNotifyArray(from: text))
        try writeWrapper(forwardingTo: forwardTarget)
        AKLog.installer.info("Codex notify wrapper installed; forwarding to \(forwardTarget.isEmpty ? "(none)" : forwardTarget.joined(separator: " "), privacy: .public)")

        // Replace or append `notify = ["<wrapper>"]`. notifyLineRange consumes
        // the trailing newline of the matched line, so always re-add one.
        let newLine = "notify = [\(quote(wrapperURL.path))]\n"
        let newText: String
        if let r = notifyLineRange(in: text) {
            newText = text.replacingCharacters(in: r, with: newLine)
        } else if text.isEmpty {
            newText = newLine
        } else if text.hasSuffix("\n") {
            newText = text + newLine
        } else {
            newText = text + "\n" + newLine
        }

        do {
            try AtomicJSONWriter.writeRaw(Data(newText.utf8), to: configURL)
        } catch {
            throw InstallError.writeFailed(error.localizedDescription)
        }
        return wrapperURL
    }

    static func uninstall() throws {
        let configURL = AppPaths.codexConfig
        guard let text = try? String(contentsOf: configURL, encoding: .utf8) else { return }
        try backup(configURL, label: "codex-config")
        let restored = readForwardingTargetFromWrapper() ?? []
        let restoredLine: String? = {
            guard !restored.isEmpty else { return nil }
            let inside = restored.map(quote).joined(separator: ", ")
            return "notify = [\(inside)]"
        }()
        let newText: String
        if let r = notifyLineRange(in: text) {
            if let restoredLine {
                newText = text.replacingCharacters(in: r, with: restoredLine)
            } else {
                // Remove the line entirely.
                var t = text
                t.removeSubrange(r)
                newText = t.replacingOccurrences(of: "\n\n\n", with: "\n\n")
            }
        } else {
            newText = text
        }
        try? AtomicJSONWriter.writeRaw(Data(newText.utf8), to: configURL)
        try? FileManager.default.removeItem(at: wrapperURL)
    }

    // MARK: - Wrapper script

    private static func writeWrapper(forwardingTo originalArray: [String]) throws {
        let hookPath = AppPaths.hookBinary.path
        var script = """
        #!/bin/bash
        # Generated by Agent Keeper. Forwards Codex notify events to the prior
        # configured program (if any) and to agentkeeper-hook.
        # Codex passes a single JSON string as $1.

        set +e

        """

        if !originalArray.isEmpty {
            // First element is the program; remaining are static prefix args
            // that should precede whatever Codex appends.
            let program = originalArray[0]
            let prefix = originalArray.dropFirst().map { shellQuote($0) }.joined(separator: " ")
            script += """
            ORIGINAL=\(shellQuote(program))
            if [ -x "$ORIGINAL" ]; then
              "$ORIGINAL" \(prefix) "$@" >/dev/null 2>&1 || true
            fi

            """
        }

        script += """
        JSON="${1:-}"
        if [ -z "$JSON" ]; then JSON='{"type":"unknown"}'; fi
        if [ -x \(shellQuote(hookPath)) ]; then
          \(shellQuote(hookPath)) codex notify "$JSON" >/dev/null 2>&1 || true
        fi
        exit 0
        """

        AppPaths.ensureDirectory(wrapperURL.deletingLastPathComponent())
        try AtomicJSONWriter.writeRaw(Data(script.utf8), to: wrapperURL)
        // chmod 755. setAttributes can silently no-op on some paths; use the
        // syscall directly to be sure.
        wrapperURL.path.withCString { _ = chmod($0, 0o755) }
    }

    /// Resolves the genuine "previous notify program" to embed in the wrapper,
    /// guaranteeing the wrapper never forwards to itself. Two cases:
    ///  - Fresh install (config points at a real prior program, or nothing):
    ///    use the config array, defensively dropping any self-reference.
    ///  - Re-install (config already points at our wrapper): the real prior
    ///    program lives inside the existing wrapper's `ORIGINAL=` line. Recover
    ///    it — and if THAT is also self-referential (a previously-corrupted
    ///    install), drop it so we write a clean, non-recursive wrapper.
    ///
    /// This makes `install()` idempotent and self-healing: `AppDelegate` invokes
    /// it on every launch, so a wrapper that was corrupted by an earlier build
    /// gets repaired automatically.
    private static func resolveForwardTarget(configArray: [String]) -> [String] {
        CodexWrapper.resolveForwardTarget(
            wrapperPath: wrapperURL.path,
            configArray: configArray,
            existingWrapperOriginal: readForwardingTargetFromWrapper() ?? []
        )
    }

    private static func samePath(_ a: String, _ b: String) -> Bool {
        CodexWrapper.samePath(a, b)
    }

    private static func readForwardingTargetFromWrapper() -> [String]? {
        guard let text = try? String(contentsOf: wrapperURL, encoding: .utf8) else { return nil }
        for line in text.split(separator: "\n") {
            let s = line.trimmingCharacters(in: .whitespaces)
            if s.hasPrefix("ORIGINAL=") {
                let raw = String(s.dropFirst("ORIGINAL=".count))
                let unquoted = unquoteShell(raw)
                return unquoted.isEmpty ? nil : [unquoted]
            }
        }
        return nil
    }

    // MARK: - TOML helpers (narrow, line-based; logic lives in CodexWrapper)

    private static func notifyLineRange(in text: String) -> Range<String.Index>? {
        CodexWrapper.notifyLineRange(in: text)
    }

    private static func extractNotifyArray(from text: String) -> [String] {
        CodexWrapper.extractNotifyArray(from: text)
    }

    private static func quote(_ s: String) -> String {
        let escaped = s.replacingOccurrences(of: "\\", with: "\\\\")
                       .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }

    private static func shellQuote(_ s: String) -> String {
        "'" + s.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    private static func unquoteShell(_ s: String) -> String {
        var t = s
        if t.hasPrefix("'") && t.hasSuffix("'") {
            t.removeFirst(); t.removeLast()
            return t.replacingOccurrences(of: "'\\''", with: "'")
        }
        if t.hasPrefix("\"") && t.hasSuffix("\"") {
            t.removeFirst(); t.removeLast()
            return t
        }
        return t
    }

    private static func backup(_ url: URL, label: String) throws {
        AppPaths.ensureDirectory(AppPaths.backupsDirectory)
        let ts = ISO8601DateFormatter().string(from: Date()).replacingOccurrences(of: ":", with: "-")
        let dst = AppPaths.backupsDirectory.appendingPathComponent("\(label).\(ts).bak", isDirectory: false)
        try? FileManager.default.copyItem(at: url, to: dst)
    }
}
